name: Publish package to test.pypi

on:
  push:
    tags:
      - "v*.*.*.dev*"
      - "v*.*.*.post*"
      - "v*.*.*.rc*"
      - "v*.*.*.a*"
      - "v*.*.*.b*"

jobs:
  pypi_test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
