name: Publish package to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pypi_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
